config/routes.rb
SampleApp::Application.routes.draw do
  get "microposts/create"
  get "microposts/destroy"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]

  get "/signin", to: 'sessions#new'
  delete "/signout", to: 'sessions#destroy'

  get "/signup", to: 'users#new'

  get "/help", to: 'static_pages#help'
  get "/about", to: 'static_pages#about'
  get "/contact", to: 'static_pages#contact'

  root "static_pages#home"

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy

  before_save { email.downcase! }
  before_create :create_remember_token 

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: { with: VALID_EMAIL_REGEX }

  validates :password, length: { minimum: 6 }
  has_secure_password

  class << self
    def new_remember_token
      SecureRandom.urlsafe_base64
    end 

    def digest(token)
      Digest::SHA1.hexdigest(token.to_s)
    end
  end

  def feed
    Micropost.where("user_id = ?", id)
  end

  private 
  def create_remember_token
    self.remember_token = self.class.digest(self.class.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :signed_in_user
  before_filter :correct_user, only: [:destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_to root_url
  end

  private
  def micropost_params
    params.require(:micropost).permit(:content)
  end

  def correct_user 
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :signed_in, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      sign_in user
      redirect_back_or(user)
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private
  def signed_in
    redirect_to root_path if signed_in?
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update, :edit, :show]
  before_action :signed_in_user, only: [:update, :edit, :index]
  before_action :authorized_user, only: [:update, :edit]
  before_action :admin_user, only: [:destroy]
  before_action :admin_self, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = target_user
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def edit
  end

  def update
    if update_successful
      flash[:success] = "You have updated your profile information."
      redirect_to @user
    else
      flash.now[:alert] = @user.errors
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def update_successful
    @user && @user.update_attributes(user_params)
  end

  def authorized_user
    redirect_to root_url unless current_user?(target_user)
  end

  def target_user
    User.find(params[:id])
  end

  def set_user
    @user = target_user
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def admin_self
    redirect_to(root_url) if current_user == target_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title)
    base_title = "Ruby on Rails Tutorial Sample App"
    unless title.empty?
      "#{base_title} | #{title}"
    else
      base_title
    end
  end

  def user_name
    signed_in? ? " | #{current_user.name}" : ""
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private
  def wrap_long_string(text, max_width = 30)
    zero_width_space = "&#8203;"
    regex = /.{1,#{max_width}}/
    (text.length < max_width) ? text :
      text.scan(regex).join(zero_width_space)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  attr_writer :current_user

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    current_user == user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"

    image_tag(gravatar_url, alt: user.name, class:"gravatar", size: options[:size])
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class:"alert alert-#{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
<p>
<a href="http://railstutorial.org/">Rails Tutorial</a>
by Michale Hartl
</p>
<nav>
<ul>
  <li><%= link_to "About", about_path %></li>
  <li><%= link_to "Contact", contact_path %></li>
  <li><a href="http://news.railstutorial.org/">News</a></li>
</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="navbar-inner">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
    <ul class="nav pull-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <% if signed_in? %>
        <%= render "layouts/signed_in_links" %>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
    </nav>
  </div>
</div>
</header>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_signed_in_links.html.erb
<li><%= link_to "Users", users_path %></li>

<li id="fat-menu" class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
  Account <b class="caret"></b>
</a>
<ul class="dropdown-menu">
  <li><%= link_to "Profile", current_user %></li>
  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
  <li class="divider"></li>
  <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
</ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title (yield :title) %> <%= user_name %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render "layouts/shim" %>
  </head>
  <body>

    <%= render "layouts/header" %>
    <div class="container">
      <%= render "layouts/flash" %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>

app/views/microposts/_micropost.html.erb
<li>
<span class="content"><%= micropost.content %></span>
<span class="timestamp">
  Posted <%= time_ago_in_words(micropost.created_at) %> ago.
</span>
<%= render "shared/delete_link", object: micropost %>
</li>

app/views/microposts/create.html.erb
<h1>Microposts#create</h1>
<p>Find me in app/views/microposts/create.html.erb</p>

app/views/microposts/destroy.html.erb
<h1>Microposts#destroy</h1>
<p>Find me in app/views/microposts/destroy.html.erb</p>

app/views/shared/_delete_link.html.erb
<% if current_user?(object.user) %>
  <%= link_to "delete", object, method: :delete, data: { confirm: "You sure?"}, title: object.content %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      <h2 class="title">
        The form contains <%= pluralize(object.errors.count, 'error') %>.
      </h2>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
<%= link_to gravatar_for(feed_item.user), feed_item.user %>
<span class="user">
  <%= link_to feed_item.user.name, feed_item.user %>
</span>
<span class="content"><%= wrap feed_item.content %></span>
<span class="timestamp">
  Post <%= time_ago_in_words(feed_item.created_at) %> ago.
</span>
<%= render "shared/delete_link", object: feed_item %>
</li>

app/views/shared/_micropost_form.html.erb
<script>
  function update_counter(text) {
    document.getElementById("character_count").innerHTML = text;
  }

  function countdown(value) {
    var max_count = 140;
    var characters_left = max_count - value.length;
    if (characters_left === 1) {
      update_counter("1 character left");
      } else {
      update_counter(characters_left.toString() + " characters left");
    }
  }
</script>

<%= form_for(@micropost) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost...", oninput:"countdown(this.value)" %>
    <p id="character_count">140 characters left</p>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: "52"), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/static_pages/_default_home.html.erb
<div class="center hero-unit">
  <h1>Sample App</h1>
  <p>
  This is the home page for the
  <a href="http://railstutorial.org/"> Ruby on Rails Tutorial </a>
  sample application.
  </p>

  <%= link_to "Sign up now!", signup_path, class: "bth btn-large btn-primary" %>
</div>

<%= link_to image_tag('rails.png', alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/static_pages/_signed_in.html.erb
<div class="row">
  <aside class="span4">
  <section>
  <%= render "shared/user_info" %>
  </section>
  <section>
  <%= render "shared/micropost_form" %>
  </section>
  </aside>

  <div class="span8">
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed' %>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide :title, "About" %>

<h1>About Us</h1>
<p>
This page will eventually say something about us
</p>

app/views/static_pages/contact.html.erb
<% provide :title, "Contact" %>

<h1>Contact Us</h1>

app/views/static_pages/help.html.erb
<% provide :title, "Help" %>
<h1>Help Page</h1>
<p>
This is the help page for my app
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <%= render "static_pages/signed_in" %>
<% else %>
  <%= render "static_pages/default_home" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit submit_text, class: "btn btn-large btn-primary" %>

<% end %>

app/views/users/_user.html.erb
<li>
<%= gravatar_for user, size: "52" %>
<%= link_to user.name, user %>
<% if current_user.admin? && !current_user?(user) %>
  | <%= link_to "delete", user, method: :delete,
    data: { confirm: "You sure?" } %>
<% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, "Edit user" %>
<h1>Update your profile</h1>


<div class="row">
  <div class="span6 offset3">
    <%= render "form", submit_text: "Save changes" %>
    <%= gravatar_for @user %>
    <%= link_to "change", "http://gravatar.com/emails", target: "_blank" %>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, "All users" %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide :title, "Sign up" %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render "form", submit_text: "Create my account" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="span4">
  <section>
  <h1>
    <%= gravatar_for @user %>
    <%= @user.name %>
  </h1>
  </section>
  </aside>
  <div class="span8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>